### ISSUE TITLE
pi64 setup pi3b getting on the internwebs

### ISSUE THREAD

**Issue by wscotgrey** [bamarni/pi64#32] opened 2017-09-06 19:34 UTC
Hey There,

First, Thanks for this. 

Just a note for your setup. 

There is no nano,vi,or gedit that is installed with the full distribution that is referenced on the read.me.

You should mention that leafpad is available for text editing.

That is important because the Wicd Network Manager drops connections in the initial setup. 

To solve this, which took all day to figure out, you have to 
`sudo leafpad /etc/network/interfaces` and then follow the code on here.
[https://learn.adafruit.com/adafruits-raspberry-pi-lesson-3-network-setup/setting-up-wifi-with-occidentalis]

This will let you input your wifi network id and password to hold the connection. 

Unfortunately, until you do this there is no accessing debian package files. 

Hope this helps
and thanks again!

**Comment by bamarni** [comment] 2017-09-07 12:03
duplicate of #33

**Closed by bamarni** 2017-09-07 12:03 UTC
